/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  JSONSchema6,
  JSONSchema7,
} from 'json-schema';


export namespace Components {

  interface AdcFormsJsonSchema {
    /**
    * The form action to be performed on submit. The method is always POST.
    */
    'action': string;
    /**
    * A CSS class (or several of them) to apply to the form.
    */
    'cssClass': string;
    /**
    * Label for the "reset" button. If none is present, the button will not be shown.
    */
    'reset': string;
    /**
    * The JSON Schema to build the form and apply validation. Accepted versions 7 and 6.
    */
    'schema': JSONSchema7 | JSONSchema6;
    /**
    * Label for the "submit" button. Defaults to "Submit"
    */
    'submit': string;
  }
  interface AdcFormsJsonSchemaAttributes extends StencilHTMLAttributes {
    /**
    * The form action to be performed on submit. The method is always POST.
    */
    'action'?: string;
    /**
    * A CSS class (or several of them) to apply to the form.
    */
    'cssClass'?: string;
    /**
    * Label for the "reset" button. If none is present, the button will not be shown.
    */
    'reset'?: string;
    /**
    * The JSON Schema to build the form and apply validation. Accepted versions 7 and 6.
    */
    'schema'?: JSONSchema7 | JSONSchema6;
    /**
    * Label for the "submit" button. Defaults to "Submit"
    */
    'submit'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdcFormsJsonSchema': Components.AdcFormsJsonSchema;
  }

  interface StencilIntrinsicElements {
    'adc-forms-json-schema': Components.AdcFormsJsonSchemaAttributes;
  }


  interface HTMLAdcFormsJsonSchemaElement extends Components.AdcFormsJsonSchema, HTMLStencilElement {}
  var HTMLAdcFormsJsonSchemaElement: {
    prototype: HTMLAdcFormsJsonSchemaElement;
    new (): HTMLAdcFormsJsonSchemaElement;
  };

  interface HTMLElementTagNameMap {
    'adc-forms-json-schema': HTMLAdcFormsJsonSchemaElement
  }

  interface ElementTagNameMap {
    'adc-forms-json-schema': HTMLAdcFormsJsonSchemaElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
