/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  JSONSchema7,
} from 'json-schema';


export namespace Components {

  interface AdcFormsJsonSchema {
    'action': string;
    'cssClass': string;
    /**
    * The JSON Schema to build the form and apply validation
    */
    'schema': JSONSchema7;
    'submit': string;
  }
  interface AdcFormsJsonSchemaAttributes extends StencilHTMLAttributes {
    'action'?: string;
    'cssClass'?: string;
    /**
    * The JSON Schema to build the form and apply validation
    */
    'schema'?: JSONSchema7;
    'submit'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AdcFormsJsonSchema': Components.AdcFormsJsonSchema;
  }

  interface StencilIntrinsicElements {
    'adc-forms-json-schema': Components.AdcFormsJsonSchemaAttributes;
  }


  interface HTMLAdcFormsJsonSchemaElement extends Components.AdcFormsJsonSchema, HTMLStencilElement {}
  var HTMLAdcFormsJsonSchemaElement: {
    prototype: HTMLAdcFormsJsonSchemaElement;
    new (): HTMLAdcFormsJsonSchemaElement;
  };

  interface HTMLElementTagNameMap {
    'adc-forms-json-schema': HTMLAdcFormsJsonSchemaElement
  }

  interface ElementTagNameMap {
    'adc-forms-json-schema': HTMLAdcFormsJsonSchemaElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
